Add Codecov to CI workflow
fyntex/drf-pagination-utils pull request #126
Opened 2023-05-23 17:46 UTC by svillegas-cdd

> Codecov is the all-in-one code coverage reporting solution for any
> test suite — giving developers actionable insights to deploy reliable
> code with confidence.

- Codecov web site: https://about.codecov.io/
- Documentation: https://docs.codecov.com/

Ref: https://cordada.aha.io/requirements/TECHINFRA-194-7
Ref: https://cordada.aha.io/features/TECHINFRA-194

2023-05-24 21:02 UTC, fpinto-cdd commented
@svillegas-cdd Can you check why the coverage files are not found? https://github.com/fyntex/drf-pagination-utils/actions/runs/5060426903/jobs/9083311035?pr=126

2023-05-24 21:38 UTC, svillegas-cdd commented
> @svillegas-cdd Can you check why the coverage files are not found? https://github.com/fyntex/drf-pagination-utils/actions/runs/5060426903/jobs/9083311035?pr=126

I haven't found why these file are not find, @jtrobles-cdd could you help me?

2023-05-24 22:44 UTC, jtrobles-cdd requested changes

2023-05-24 22:44 UTC, jtrobles-cdd commented on .github/workflows/ci.yaml
> +          directory: ./test-reports/coverage/
```suggestion
          directory: ./test_reports/coverage/
```

2023-05-24 22:44 UTC, jtrobles-cdd commented on setup.cfg
> +output = test-reports/coverage/xml/coverage.xml
Move this to `.coveragerc.test.ini` and change it to:

```suggestion
[xml]
output = test_reports/coverage/xml/coverage.xml
```

2023-05-24 22:44 UTC, jtrobles-cdd commented
> > @svillegas-cdd Can you check why the coverage files are not found? https://github.com/fyntex/drf-pagination-utils/actions/runs/5060426903/jobs/9083311035?pr=126
> 
> I haven't found why these file are not find, @jtrobles-cdd could you help me?

See https://github.com/fyntex/drf-pagination-utils/pull/126#pullrequestreview-1442841577.

2023-05-25 15:58 UTC, fpinto-cdd approved these changes

2023-06-02 20:54 UTC, jtrobles-cdd requested changes
- [ ] URL of Aha requirement is for a different VCS repository. Please fix PR description and commit messages.

2023-06-02 20:54 UTC, jtrobles-cdd commented on .coveragerc.test.ini
> +output = test_reports/coverage/xml/coverage.xml
Can you move this between `[report]` and `[html]`?

2023-06-02 20:54 UTC, jtrobles-cdd commented on .github/workflows/ci.yaml
> +        uses: codecov/codecov-action@v3.1.2
```suggestion
        uses: codecov/codecov-action@v3.1.4
```

2023-06-02 20:54 UTC, jtrobles-cdd commented on README.md
> +|---------------------------------------------------------------------------------------------------------------------------------------------------|
```suggestion
| Code Coverage |
| ------------- |
```

2023-06-02 20:54 UTC, jtrobles-cdd commented on README.md
> +| [![Codecov](https://codecov.io/gh/fyntex/drf-pagination-utils/branch/develop/graph/badge.svg)](https://codecov.io/gh/fyntex/drf-pagination-utils) |
```suggestion
| [![Codecov](https://codecov.io/gh/fyntex/drf-pagination-utils/branch/develop/graph/badge.svg?token=66RN4HVW2C)](https://codecov.io/gh/fyntex/drf-pagination-utils) |
```

2023-06-05 15:41 UTC, jtrobles-cdd approved these changes

2023-06-05 18:14 UTC, merged